from django.core.management.base import BaseCommand
from game.models import Scenario


class Command(BaseCommand):
    help = 'Popula o banco de dados com cenários do jogo político'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Limpa todos os cenários existentes antes de criar novos',
        )

    def handle(self, *args, **options):
        if options['clear']:
            count = Scenario.objects.count()
            Scenario.objects.all().delete()
            self.stdout.write(f'🗑️  {count} cenários existentes removidos.')

        scenarios_data = [
            # PAR_1 - Eficiência econômica vs. direitos trabalhistas
            {
                'par': 'PAR_1',
                'numero': 1,
                'codigo': 'ECO-001',
                'titulo': 'Demissão em Massa na Fábrica',
                'contexto': 'A maior fábrica da cidade, berço de sustento para 5.000 famílias por três gerações, está prestes a fechar as portas. O dono propõe sacrificar 3.000 empregos para salvar os outros 2.000. Sem essa medida, a cidade inteira pode afundar em ruínas e silêncio, como um cemitério industrial.',
                'dilema': 'Você aceita a perda de milhares de empregos agora para tentar salvar o que resta da cidade?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': -1,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Eficiência econômica vs. direitos trabalhistas'
            },
            {
                'par': 'PAR_1',
                'numero': 2,
                'codigo': 'ECO-002',
                'titulo': 'Subsídio vs Assistência Social',
                'contexto': 'O cofre público tem R$ 500 milhões. Esse valor pode impulsionar empresas e prometer prosperidade futura ou, hoje mesmo, colocar comida no prato de 100.000 famílias famintas. No salão do congresso, empresários acenam com cifras e projeções, enquanto do lado de fora mães imploram com crianças ao colo.',
                'dilema': 'Você aposta no futuro econômico distante ou na sobrevivência imediata de milhares de famílias?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': -1,
                'impacto_empate_liberdade': 0,
                'tema': 'Eficiência econômica vs. direitos trabalhistas'
            },

            # PAR_2 - Segurança pública vs. liberdades civis
            {
                'par': 'PAR_2',
                'numero': 3,
                'codigo': 'SEG-001',
                'titulo': 'Toque de Recolher após Assassinatos',
                'contexto': 'Um assassino em série aterroriza a cidade, matando sempre depois das 22h. Doze vidas já foram ceifadas. A polícia exige toque de recolher, transformando as ruas em deserto noturno. Pode salvar vidas, mas também sufocar a rotina de quem depende da noite para viver.',
                'dilema': 'Você fecha a cidade à noite em nome da segurança, mesmo que isso custe liberdade e sustento de muitos?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': -1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': 1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': -1,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Segurança pública vs. liberdades civis'
            },
            {
                'par': 'PAR_2',
                'numero': 4,
                'codigo': 'SEG-002',
                'titulo': 'Câmeras com Reconhecimento Facial',
                'contexto': 'Um projeto prevê instalar 50.000 câmeras inteligentes, capazes de identificar criminosos em segundos. A promessa é reduzir a criminalidade em 70%. Mas cada passo, cada rosto, cada encontro será registrado. Um paraíso para quem busca ordem. Um pesadelo para quem teme o fim da privacidade.',
                'dilema': 'Você permite que a cidade seja vigiada por olhos eletrônicos em troca de ruas mais seguras?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': -1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': 1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': -1,
                'tema': 'Segurança pública vs. liberdades civis'
            },

            # PAR_3 - Meio ambiente vs. desenvolvimento econômico
            {
                'par': 'PAR_3',
                'numero': 5,
                'codigo': 'AMB-001',
                'titulo': 'Mineração na Reserva Ancestral',
                'contexto': 'A última floresta intocada da região esconde trilhões em minérios raros, suficientes para transformar o país em potência tecnológica. Mas é também o último refúgio de 12 tribos ancestrais e centenas de espécies únicas. As escavadeiras esperam na fronteira, enquanto líderes indígenas fazem vigília em torno das árvores sagradas.',
                'dilema': 'Você autoriza a destruição do último santuário natural em nome do progresso tecnológico nacional?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': -1,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Meio ambiente vs. desenvolvimento econômico'
            },
            {
                'par': 'PAR_3',
                'numero': 6,
                'codigo': 'AMB-002',
                'titulo': 'Usina Nuclear na Costa',
                'contexto': 'O país sofre com apagões constantes que paralisam hospitais e escolas. Uma usina nuclear poderia resolver a crise energética para sempre, mas será construída a 5 km de uma cidade de 200.000 habitantes. Os engenheiros garantem segurança total. As famílias locais fazem as malas, lembrando-se de Chernobyl.',
                'dilema': 'Você constrói a usina que pode iluminar o futuro, mesmo correndo o risco de criar uma zona morta?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': -1,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Meio ambiente vs. desenvolvimento econômico'
            },

            # PAR_4 - Saúde pública vs. economia
            {
                'par': 'PAR_4',
                'numero': 7,
                'codigo': 'SAU-001',
                'titulo': 'Lockdown Total na Pandemia',
                'contexto': 'Um vírus letal devora vidas como fogo em palha seca. Os hospitais imploram por lockdown total - único freio contra o colapso completo. Mas nas ruas, pequenos comerciantes choram diante de suas lojas fechadas, calculando quantos dias ainda conseguem alimentar os filhos. A escolha é entre salvar vidas hoje ou preservar o sustento de amanhã.',
                'dilema': 'Você paralisa completamente a economia para conter a morte, mesmo sabendo que isso pode gerar miséria duradoura?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': -1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': 1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': -1,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': -1,
                'impacto_empate_liberdade': 0,
                'tema': 'Saúde pública vs. economia'
            },
            {
                'par': 'PAR_4',
                'numero': 8,
                'codigo': 'SAU-002',
                'titulo': 'Medicamento Experimental em Crianças',
                'contexto': 'Uma doença rara condena 500 crianças à morte certa em seis meses. Existe um medicamento experimental, testado apenas em adultos, que pode salvá-las - ou causar efeitos colaterais devastadores. Os pais se agarram a qualquer esperança. Os médicos tremem diante da responsabilidade. O tempo escorre como areia entre os dedos.',
                'dilema': 'Você autoriza o uso do medicamento não testado, apostando tudo numa corrida contra a morte?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 0,
                'impacto_sim_liberdade': 1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': -1,
                'impacto_empate_liberdade': 0,
                'tema': 'Saúde pública vs. economia'
            },

            # PAR_5 - Educação vs. tradição cultural
            {
                'par': 'PAR_5',
                'numero': 9,
                'codigo': 'EDU-001',
                'titulo': 'Educação Sexual Obrigatória',
                'contexto': 'Adolescentes morrem em abortos clandestinos. DSTs se espalham como praga silenciosa. Especialistas clamam por educação sexual obrigatória nas escolas, única forma de brecar a tragédia. Mas milhares de famílias conservadoras ameaçam retirar os filhos do sistema público, alegando que a escola quer roubar a inocência de suas crianças.',
                'dilema': 'Você impõe a educação sexual contra a vontade das famílias para salvar vidas jovens?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': 0,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': -1,
                'impacto_empate_liberdade': 0,
                'tema': 'Educação vs. tradição cultural'
            },
            {
                'par': 'PAR_5',
                'numero': 10,
                'codigo': 'EDU-002',
                'titulo': 'Idioma Nacional vs Idiomas Locais',
                'contexto': 'O país tem 47 idiomas regionais, patrimônio de séculos que se apaga a cada geração. O governo propõe preservá-los tornando-os obrigatórios nas escolas locais. Mas isso significa menos tempo para matemática, ciências e o idioma nacional - prejudicando a competitividade dos estudantes no mercado globalizado.',
                'dilema': 'Você sacrifica a eficiência educacional para manter vivas as línguas que carregam a alma dos povos?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': 0,
                'impacto_sim_economia': -1,
                'impacto_sim_liberdade': 1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': 0,
                'impacto_nao_economia': 1,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Educação vs. tradição cultural'
            },

            # PAR_6 - Imigração vs. identidade nacional
            {
                'par': 'PAR_6',
                'numero': 11,
                'codigo': 'IMI-001',
                'titulo': 'Refugiados na Fronteira',
                'contexto': 'Cinquenta mil refugiados aguardam na fronteira, fugindo de uma guerra civil sangrenta. Chegam apenas com as roupas do corpo e o desespero nos olhos. Acolhê-los significa dividir recursos já escassos, competir por empregos em tempos de crise. Rejeitá-los significa condená-los à morte certa nos campos de batalha.',
                'dilema': 'Você abre as portas do país para salvar vidas, mesmo sabendo que isso pode abalar a estabilidade interna?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': -1,
                'impacto_sim_liberdade': 1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': 1,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': -1,
                'impacto_empate_liberdade': 0,
                'tema': 'Imigração vs. identidade nacional'
            },
            {
                'par': 'PAR_6',
                'numero': 12,
                'codigo': 'IMI-002',
                'titulo': 'Integração Forçada vs Multiculturalismo',
                'contexto': 'Comunidades de imigrantes vivem isoladas há décadas, mantendo costumes que chocam com valores locais. Alguns praticam casamentos arranjados, outros segregam mulheres. O dilema é brutal: forçar a assimilação aos valores nacionais, destruindo identidades ancestrais, ou permitir práticas que ferem direitos humanos básicos.',
                'dilema': 'Você impõe a integração cultural forçada para proteger direitos, mesmo que isso destrua tradições milenares?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': 0,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Imigração vs. identidade nacional'
            },

            # PAR_7 - Transparência vs. segurança nacional
            {
                'par': 'PAR_7',
                'numero': 13,
                'codigo': 'TRA-001',
                'titulo': 'Vazamento de Documentos Secretos',
                'contexto': 'Um hacker invadiu arquivos militares e ameaça expor operações secretas que salvaram milhares de vidas, mas violaram leis internacionais. A revelação pode destruir alianças estratégicas e expor agentes infiltrados à morte. Silenciar o vazamento protege vidas, mas esconde crimes de guerra do escrutínio público.',
                'dilema': 'Você censura a verdade para proteger vidas e alianças, ou permite que o mundo veja os crimes cometidos em seu nome?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': 0,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': -1,
                'impacto_empate_liberdade': 0,
                'tema': 'Transparência vs. segurança nacional'
            },
            {
                'par': 'PAR_7',
                'numero': 14,
                'codigo': 'TRA-002',
                'titulo': 'Investigação do Presidente',
                'contexto': 'Evidências apontam que o presidente pode ter desviado fundos de emergência durante a pandemia. Uma investigação completa revelaria a verdade, mas também paralisaria o governo em momento crítico de reconstrução econômica. O país precisa de liderança estável, mas também de justiça. A balança treme entre governabilidade e moralidade.',
                'dilema': 'Você sacrifica a estabilidade do governo para investigar possível corrupção, mesmo em meio a uma crise nacional?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': 0,
                'impacto_sim_economia': -1,
                'impacto_sim_liberdade': 1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': 0,
                'impacto_nao_economia': 1,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Transparência vs. segurança nacional'
            },

            # PAR_8 - Justiça vs. ordem social
            {
                'par': 'PAR_8',
                'numero': 15,
                'codigo': 'JUS-001',
                'titulo': 'Pena de Morte para Serial Killer',
                'contexto': 'Um assassino confesso matou 20 crianças com requintes de crueldade. Não há dúvida sobre sua culpa. As famílias das vítimas clamam por sua execução. Abolir a pena de morte seria seguir princípios humanitários, mas também negar justiça às famílias destroçadas e talvez incentivar outros monstros.',
                'dilema': 'Você autoriza a execução do assassino para fazer justiça às vítimas, ou preserva a vida mesmo do mais cruel dos criminosos?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': 0,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': -1,
                'impacto_empate_liberdade': 0,
                'tema': 'Justiça vs. ordem social'
            },
            {
                'par': 'PAR_8',
                'numero': 16,
                'codigo': 'JUS-002',
                'titulo': 'Anistia para Presos Políticos',
                'contexto': 'Milhares de presos políticos apodrecem nas cadeias do regime anterior. Libertá-los seria justiça histórica, mas muitos cometeram atos terroristas que vitimaram inocentes. Suas liberdades podem inspirar outros extremistas ou finalmente curar as feridas nacionais. O perdão pode ser sabedoria ou ingenuidade fatal.',
                'dilema': 'Você liberta os presos políticos para reconciliar o país, mesmo correndo o risco de despertar fantasmas violentos do passado?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 0,
                'impacto_sim_liberdade': 1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Justiça vs. ordem social'
            },

            # PAR_9 - Tecnologia vs. privacidade
            {
                'par': 'PAR_9',
                'numero': 17,
                'codigo': 'TEC-001',
                'titulo': 'Inteligência Artificial na Justiça',
                'contexto': 'Uma IA revolucionária pode analisar processos judiciais em minutos, eliminando anos de espera por justiça. Promete reduzir a desigualdade no sistema legal e acelerar julgamentos. Mas algoritmos carregam preconceitos ocultos, e uma decisão errada pode arruinar vidas inocentes. A eficiência tecnológica se choca com a sabedoria humana.',
                'dilema': 'Você entrega a justiça a máquinas perfeitas mas frias, ou mantém juízes humanos imperfeitos mas compassivos?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 0,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': 0,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Tecnologia vs. privacidade'
            },
            {
                'par': 'PAR_9',
                'numero': 18,
                'codigo': 'TEC-002',
                'titulo': 'Controle da Internet',
                'contexto': 'Notícias falsas destroem reputações e incitam violência. Teorias conspiratórias levam pessoas ao suicídio. A internet se tornou um campo de batalha de desinformação. Controlar o conteúdo online pode salvar mentes vulneráveis, mas também abrir caminho para censura autoritária. A linha entre proteção e opressão é mais fina que um fio de navalha.',
                'dilema': 'Você regula o que as pessoas podem ver online para protegê-las da mentira, mesmo que isso limite sua liberdade de escolher?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': -1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': 1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Tecnologia vs. privacidade'
            },

            # PAR_10 - Religião vs. secularismo
            {
                'par': 'PAR_10',
                'numero': 19,
                'codigo': 'REL-001',
                'titulo': 'Símbolos Religiosos em Prédios Públicos',
                'contexto': 'Cruzes e símbolos religiosos adornam escolas e tribunais há séculos, testemunhas silenciosas da história nacional. Grupos laicos exigem sua remoção, alegando que o Estado deve ser neutro. Fiéis ameaçam guerra cultural se a fé for expulsa dos espaços públicos. A tradição se choca com a diversidade em praça pública.',
                'dilema': 'Você remove os símbolos sagrados para respeitar todas as crenças, ou os mantém para honrar as raízes culturais do país?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 0,
                'impacto_sim_liberdade': 1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Religião vs. secularismo'
            },
            {
                'par': 'PAR_10',
                'numero': 20,
                'codigo': 'REL-002',
                'titulo': 'Casamento Religioso vs Civil',
                'contexto': 'Casais do mesmo sexo lutam pelo direito ao casamento há décadas. Legalizar o casamento igualitário garantiria direitos fundamentais, mas enfureceria comunidades religiosas que veem nisso um ataque aos valores sagrados. Templos ameaçam fechar as portas. Famílias se dividem. O amor se debate entre a lei dos homens e a lei divina.',
                'dilema': 'Você legaliza o casamento igualitário para garantir direitos iguais, mesmo que isso cause uma ruptura social com comunidades religiosas?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 0,
                'impacto_sim_liberdade': 1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Religião vs. secularismo'
            },
            {
                'par': 'PAR_11',
                'numero': 21,
                'codigo': 'AGR-001',
                'titulo': 'Desapropriação de Terras Ancestrais',
                'contexto': 'Famílias camponesas cultivam a mesma terra há cinco gerações, mas produzem apenas para subsistência. Agronegócios oferecem tecnologia e empregos, prometendo alimentar milhões. Expulsar os pequenos agricultores pode resolver a fome nacional, mas também apagar a memória de quem fez a terra florescer com as próprias mãos por séculos.',
                'dilema': 'Você entrega as terras ao agronegócio para alimentar multidões, mesmo que isso destrua o modo de vida de milhares de famílias?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Agricultura vs. urbanização'
            },
            {
                'par': 'PAR_11',
                'numero': 22,
                'codigo': 'AGR-002',
                'titulo': 'Metrópole sobre Campos Férteis',
                'contexto': 'A capital explode em população, sufocando em favelas e poluição. A única área para expansão são os campos mais férteis do país, capazes de alimentar 10 milhões de pessoas. Construir a nova metrópole daria moradia digna a 3 milhões de refugiados urbanos, mas condenaria o país à dependência alimentar eterna.',
                'dilema': 'Você sacrifica a segurança alimentar futura para resolver a crise habitacional presente?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 0,
                'impacto_sim_liberdade': 1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': -1,
                'impacto_empate_liberdade': 0,
                'tema': 'Agricultura vs. urbanização'
            },

            # PAR_12 - Direitos dos idosos vs. juventude
            {
                'par': 'PAR_12',
                'numero': 23,
                'codigo': 'IDA-001',
                'titulo': 'Aposentadoria vs Educação Infantil',
                'contexto': 'O país envelhece rapidamente. Idosos que construíram a nação exigem aposentadoria digna, mas os cofres estão secos. O mesmo dinheiro pode garantir pensões decentes ou construir escolas para 2 milhões de crianças. Escolher os velhos pode condenar os jovens. Escolher os jovens pode trair quem já deu tudo pela pátria.',
                'dilema': 'Você garante aposentadoria digna aos idosos ou investe na educação das crianças?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': -1,
                'impacto_sim_liberdade': 0,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': 1,
                'impacto_nao_liberdade': 0,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Direitos dos idosos vs. juventude'
            },
            {
                'par': 'PAR_12',
                'numero': 24,
                'codigo': 'IDA-002',
                'titulo': 'Eutanásia para Alívio do Sistema',
                'contexto': 'Hospitais transbordam com idosos terminais em sofrimento extremo. Famílias se endividam para manter entes queridos ligados a máquinas. Legalizar a eutanásia pode encerrar a agonia e liberar recursos para salvar quem ainda tem chance. Mas também pode abrir precedente para eliminar os "indesejados" da sociedade.',
                'dilema': 'Você permite que idosos escolham a morte digna, mesmo sabendo que isso pode ser distorcido em eliminação dos vulneráveis?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': 0,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': 1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': 0,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Direitos dos idosos vs. juventude'
            },

            # PAR_13 - Soberania nacional vs. globalização
            {
                'par': 'PAR_13',
                'numero': 25,
                'codigo': 'SOB-001',
                'titulo': 'Empresa Nacional vs Multinacional',
                'contexto': 'A única montadora nacional está falindo, vítima da concorrência global. Salvá-la custaria 50 bilhões e manteria 200 mil empregos nacionais. Deixar falir permitiria que multinacionais eficientes assumissem, oferecendo carros melhores e mais baratos. Orgulho nacional se debate contra pragmatismo econômico.',
                'dilema': 'Você gasta bilhões para manter a empresa nacional viva ou permite que estrangeiros dominem o mercado?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 0,
                'impacto_sim_economia': -1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': 0,
                'impacto_nao_economia': 1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Soberania nacional vs. globalização'
            },
            {
                'par': 'PAR_13',
                'numero': 26,
                'codigo': 'SOB-002',
                'titulo': 'Acordo Comercial Assimétrico',
                'contexto': 'Uma superpotência oferece acordo comercial que daria acesso a mercados trilionários, mas exige que o país abra completamente suas fronteiras econômicas. O acordo pode gerar prosperidade inédita, mas também tornar o país eternamente dependente de decisões tomadas em capitais estrangeiras.',
                'dilema': 'Você aceita a prosperidade sob tutela econômica estrangeira ou mantém a independência nacional mesmo na pobreza?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Soberania nacional vs. globalização'
            },

            # PAR_14 - Ciência vs. ética
            {
                'par': 'PAR_14',
                'numero': 27,
                'codigo': 'CIE-001',
                'titulo': 'Pesquisa com Embriões Humanos',
                'contexto': 'Cientistas descobriram como curar doenças genéticas devastadoras usando embriões humanos em pesquisa. Podem salvar milhões de futuras crianças de vidas de sofrimento. Mas cada experimento destrói embriões que alguns consideram vidas humanas. A fronteira entre salvar o futuro e cometer homicídio se torna nebulosa.',
                'dilema': 'Você autoriza experimentos com embriões para curar doenças genéticas, mesmo que isso signifique destruir potenciais vidas humanas?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': 0,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': 0,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Ciência vs. ética'
            },
            {
                'par': 'PAR_14',
                'numero': 28,
                'codigo': 'CIE-002',
                'titulo': 'Modificação Genética de Bebês',
                'contexto': 'Tecnologia CRISPR permite eliminar deficiências genéticas antes do nascimento, criando bebês perfeitos. Pais ricos poderão comprar filhos superinteligentes e super-resistentes, enquanto pobres terão crianças "defeituosas". A eugenia retorna travestida de progresso científico, prometendo eliminar sofrimento mas criando castas genéticas.',
                'dilema': 'Você permite a modificação genética de bebês para eliminar doenças, sabendo que isso pode criar uma sociedade geneticamente dividida?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': 0,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': 0,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Ciência vs. ética'
            },

            # PAR_15 - Militar vs. civil
            {
                'par': 'PAR_15',
                'numero': 29,
                'codigo': 'MIL-001',
                'titulo': 'Golpe para Salvar a Democracia',
                'contexto': 'Um presidente eleito democraticamente se torna ditador, fechando o congresso e prendendo opositores. As forças armadas oferecem um golpe "cirúrgico" para remover o tirano e restaurar a democracia. Quebrar a ordem constitucional pode salvar a constituição, mas também legitimar futuras intervenções militares.',
                'dilema': 'Você apoia o golpe militar contra o ditador democraticamente eleito para salvar a democracia?',
                'impacto_sim_estabilidade': 0,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': -1,
                'impacto_sim_liberdade': 0,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': -1,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Militar vs. civil'
            },
            {
                'par': 'PAR_15',
                'numero': 30,
                'codigo': 'MIL-002',
                'titulo': 'Orçamento Militar vs Social',
                'contexto': 'Países vizinhos se armam pesadamente, ameaçando a soberania nacional. Generais exigem 40% do orçamento para modernizar as forças armadas e proteger as fronteiras. Esse mesmo dinheiro poderia construir hospitais e escolas. Escolher a defesa pode salvar o país. Escolher o social pode deixá-lo indefeso.',
                'dilema': 'Você prioriza o fortalecimento militar para proteger o país ou investe em saúde e educação para melhorar a vida do povo?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': -1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': -1,
                'impacto_empate_liberdade': 0,
                'tema': 'Militar vs. civil'
            },

            # PAR_16 - Energia vs. sustentabilidade
            {
                'par': 'PAR_16',
                'numero': 31,
                'codigo': 'ENE-001',
                'titulo': 'Carvão vs Energias Renováveis',
                'contexto': 'Reservas de carvão podem gerar energia barata por 200 anos, mantendo indústrias e empregos. Mas também acelerar o aquecimento global e condenar as próximas gerações a um planeta inabitável. Energias renováveis são limpas, mas custam 10 vezes mais e podem falir o país antes de salvá-lo.',
                'dilema': 'Você queima carvão para manter a economia funcionando hoje ou aceita a crise econômica para salvar o planeta amanhã?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 0,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': 0,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': 0,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Energia vs. sustentabilidade'
            },
            {
                'par': 'PAR_16',
                'numero': 32,
                'codigo': 'ENE-002',
                'titulo': 'Hidrelétrica na Terra Indígena',
                'contexto': 'Uma hidrelétrica gigante pode fornecer energia limpa para 50 milhões de pessoas, mas inundará terras sagradas de 5 tribos indígenas. Os índios oferecem resistência armada. A obra pode democratizar a eletricidade e impulsionar o desenvolvimento, mas também apagar culturas milenares sob águas artificiais.',
                'dilema': 'Você constrói a hidrelétrica para levar progresso ao país, mesmo que isso destrua o lar ancestral de povos indígenas?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': -1,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Energia vs. sustentabilidade'
            },

            # PAR_17 - Drogas vs. saúde pública
            {
                'par': 'PAR_17',
                'numero': 33,
                'codigo': 'DRO-001',
                'titulo': 'Legalização da Maconha',
                'contexto': 'Prisões explodem com pequenos traficantes, custando bilhões e destruindo famílias. Legalizar a maconha pode esvaziar cadeias, gerar impostos e reduzir violência. Mas também pode normalizar drogas e facilitar o acesso de menores. O dilema se equilibra entre liberdade individual e proteção coletiva.',
                'dilema': 'Você legaliza a maconha para reduzir a violência e encarceramentos, mesmo correndo o risco de aumentar o consumo geral?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': 0,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': 1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': 0,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Drogas vs. saúde pública'
            },
            {
                'par': 'PAR_17',
                'numero': 34,
                'codigo': 'DRO-002',
                'titulo': 'Internação Compulsória de Dependentes',
                'contexto': 'Viciados em crack vagam como zumbis pelas ruas, perdidos para suas famílias e para si mesmos. Internação compulsória pode salvá-los da morte certa, mas viola sua autonomia e liberdade. Deixá-los livres respeita sua escolha, mas os condena à degradação total. Amor e controle se confundem em decisão impossível.',
                'dilema': 'Você força dependentes químicos ao tratamento contra sua vontade para salvá-los, ou respeita sua liberdade de se destruir?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': -1,
                'impacto_sim_liberdade': -1,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': 1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Drogas vs. saúde pública'
            },

            # PAR_18 - Transporte vs. meio ambiente
            {
                'par': 'PAR_18',
                'numero': 35,
                'codigo': 'TRA-001',
                'titulo': 'Rodovia pelo Parque Nacional',
                'contexto': 'Uma rodovia cortando o parque nacional reduziria em 4 horas a viagem entre duas capitais, impulsionando comércio e turismo. Mas fragmentaria o último corredor ecológico do país, condenando jaguares e outras espécies à extinção. O asfalto pode conectar pessoas, mas desconectar para sempre a natureza.',
                'dilema': 'Você autoriza a rodovia para facilitar o desenvolvimento regional, mesmo que isso fragmente o último santuário da vida selvagem?',
                'impacto_sim_estabilidade': 1,
                'impacto_sim_seguranca': 0,
                'impacto_sim_economia': 1,
                'impacto_sim_liberdade': 0,
                'impacto_nao_estabilidade': -1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': -1,
                'impacto_nao_liberdade': 0,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Transporte vs. meio ambiente'
            },
            {
                'par': 'PAR_18',
                'numero': 36,
                'codigo': 'TRA-002',
                'titulo': 'Carros Elétricos vs Combustão',
                'contexto': 'A indústria automobilística nacional emprega 2 milhões de pessoas produzindo carros a combustão. Forçar a transição para elétricos salvaria o meio ambiente, mas destruiria a cadeia produtiva tradicional. Milhares de mecânicos, postos de gasolina e metalúrgicas ficariam obsoletos da noite para o dia.',
                'dilema': 'Você força a transição para carros elétricos para salvar o meio ambiente, mesmo que isso destrua milhões de empregos tradicionais?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': 1,
                'impacto_sim_economia': -1,
                'impacto_sim_liberdade': 0,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': -1,
                'impacto_nao_economia': 1,
                'impacto_nao_liberdade': 0,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Transporte vs. meio ambiente'
            },

            # PAR_19 - Habitação vs. patrimônio histórico
            {
                'par': 'PAR_19',
                'numero': 37,
                'codigo': 'HAB-001',
                'titulo': 'Demolição do Centro Histórico',
                'contexto': 'O centro histórico da cidade, patrimônio de 300 anos, abriga apenas 500 famílias ricas em casarões coloniais. Demolir tudo permitiria construir habitação social para 50.000 pessoas. Preservar a história mantém privilégios de poucos. Destruí-la apaga a memória nacional para sempre.',
                'dilema': 'Você demole o patrimônio histórico para dar moradia a milhares de famílias carentes?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': 0,
                'impacto_sim_economia': 0,
                'impacto_sim_liberdade': 1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': 0,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': -1,
                'impacto_empate_liberdade': 0,
                'tema': 'Habitação vs. patrimônio histórico'
            },
            {
                'par': 'PAR_19',
                'numero': 38,
                'codigo': 'HAB-002',
                'titulo': 'Ocupação de Prédios Abandonados',
                'contexto': 'Milhares de prédios comerciais ficaram vazios após a crise econômica, enquanto 100.000 pessoas dormem nas ruas. Autorizar ocupações daria teto imediato aos sem-teto, mas violaria direitos de propriedade e criaria precedente perigoso. Respeitar a propriedade mantém ordem, mas perpetua a miséria urbana.',
                'dilema': 'Você permite a ocupação de prédios abandonados pelos sem-teto, mesmo que isso viole o direito à propriedade privada?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 0,
                'impacto_sim_liberdade': 1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': -1,
                'impacto_empate_liberdade': 0,
                'tema': 'Habitação vs. patrimônio histórico'
            },

            # PAR_20 - Mídia vs. verdade
            {
                'par': 'PAR_20',
                'numero': 39,
                'codigo': 'MID-001',
                'titulo': 'Monopólio da Informação',
                'contexto': 'Três famílias controlam 90% da mídia nacional, moldando opiniões e decidindo eleições. Quebrar o monopólio democratizaria a informação, mas também abriria espaço para fake news e propaganda extremista. Manter o controle garante qualidade jornalística, mas perpetua manipulação das massas.',
                'dilema': 'Você quebra o monopólio midiático para democratizar a informação, mesmo correndo o risco de espalhar desinformação?',
                'impacto_sim_estabilidade': -1,
                'impacto_sim_seguranca': -1,
                'impacto_sim_economia': 0,
                'impacto_sim_liberdade': 1,
                'impacto_nao_estabilidade': 1,
                'impacto_nao_seguranca': 1,
                'impacto_nao_economia': 0,
                'impacto_nao_liberdade': -1,
                'impacto_empate_estabilidade': 0,
                'impacto_empate_seguranca': 0,
                'impacto_empate_economia': 0,
                'impacto_empate_liberdade': 0,
                'tema': 'Mídia vs. verdade'
            },
        ]

        # Criar todos os cenários
        created_count = 0
        for data in scenarios_data:
            scenario, created = Scenario.objects.get_or_create(
                codigo=data['codigo'],
                defaults=data
            )
            if created:
                created_count += 1
                self.stdout.write(f"✅ {scenario.codigo} - {scenario.titulo}")
            else:
                self.stdout.write(f"⚠️  {scenario.codigo} já existe")

        self.stdout.write(
            self.style.SUCCESS(f'\n🎯 {created_count} novos cenários criados!')
        )

        # Resumo dos pares
        self.stdout.write('\n📊 Resumo dos pares:')
        pares = {}
        for data in scenarios_data:
            par = data['par']
            if par not in pares:
                pares[par] = []
            pares[par].append(data['titulo'])

        for par, titulos in pares.items():
            self.stdout.write(f"\n{par}:")
            for titulo in titulos:
                self.stdout.write(f"  - {titulo}")

        self.stdout.write(f'\n📈 Total de cenários no banco: {Scenario.objects.count()}')