# Generated by Django 5.2.5 on 2025-08-13 02:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sessao', models.CharField(max_length=200, verbose_name='Nome da Sessão')),
                ('tipo_comunicacao', models.CharField(choices=[('SIM', 'Com Comunicação'), ('NAO', 'Sem Comunicação')], max_length=3, verbose_name='Tipo de Comunicação')),
                ('status', models.CharField(choices=[('COMPLETO', 'Completado (6 rounds)'), ('INTERROMPIDO', 'Interrompido (colapso)')], max_length=15, verbose_name='Status')),
                ('rounds_completados', models.IntegerField(verbose_name='Rounds Completados')),
                ('estabilidade_final', models.IntegerField(verbose_name='Estabilidade Final')),
                ('seguranca_final', models.IntegerField(verbose_name='Segurança Final')),
                ('economia_final', models.IntegerField(verbose_name='Economia Final')),
                ('liberdade_final', models.IntegerField(verbose_name='Liberdade Final')),
                ('pontuacoes_individuais', models.JSONField(verbose_name='Pontuações Individuais')),
                ('pontuacoes_coletivas', models.JSONField(verbose_name='Pontuações Coletivas')),
                ('total_consensos', models.IntegerField(default=0, verbose_name='Total de Consensos')),
                ('total_empates', models.IntegerField(default=0, verbose_name='Total de Empates')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Sessão de Jogo',
                'verbose_name_plural': 'Sessões de Jogo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada_atual', models.IntegerField(default=1)),
                ('estabilidade', models.IntegerField(default=3)),
                ('seguranca', models.IntegerField(default=3)),
                ('economia', models.IntegerField(default=3)),
                ('liberdade', models.IntegerField(default=3)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('papel', models.CharField(max_length=100)),
                ('pontuacao_individual', models.IntegerField(default=0)),
                ('pontuacao_coletiva', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('numero', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('contexto', models.TextField()),
                ('dilema', models.TextField()),
                ('impacto_sim_estabilidade', models.IntegerField()),
                ('impacto_sim_seguranca', models.IntegerField()),
                ('impacto_sim_economia', models.IntegerField()),
                ('impacto_sim_liberdade', models.IntegerField()),
                ('impacto_nao_estabilidade', models.IntegerField()),
                ('impacto_nao_seguranca', models.IntegerField()),
                ('impacto_nao_economia', models.IntegerField()),
                ('impacto_nao_liberdade', models.IntegerField()),
                ('impacto_empate_estabilidade', models.IntegerField()),
                ('impacto_empate_seguranca', models.IntegerField()),
                ('impacto_empate_economia', models.IntegerField()),
                ('impacto_empate_liberdade', models.IntegerField()),
                ('tema', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('alinhado', models.BooleanField(default=False)),
                ('impacto', models.JSONField(blank=True, null=True)),
                ('pontos_ganhos', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.round')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.scenario'),
        ),
    ]
